"""added age to fighter

Revision ID: 6aa65f6cffac
Revises: 17f598e15c23
Create Date: 2023-07-17 09:55:44.675806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aa65f6cffac'
down_revision = '17f598e15c23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fighters', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fighters', 'age')
    # ### end Alembic commands ###
